//Login
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

// Sidebar Menu
export const MENU_OPEN = "MENU_OPEN";
export const MENU_CLOSE = "MENU_CLOSE";

// Impact Based
export const STORE_IMPACT_TESTCASES = "STORE_IMPACT_TESTCASES";

//Pair-wise
export const STORE_ALL_BUSINESS_PROCESS = "STORE_ALL_BUSINESS_PROCESS";
export const STORE_BUSINESS_PROCESS = "STORE_BUSINESS_PROCESS";
export const UPDATE_BUSINESS_PROCESS = "UPDATE_BUSINESS_PROCESS";
export const PICK_BUSINESS_PROCESS = "PICK_BUSINESS_PROCESS";
export const PICK_DOMAIN = "PICK_DOMAIN";
export const EDIT_BUSINESS_PROCESS = "EDIT_BUSINESS_PROCESS";
export const DELETE_BUSINESS_PROCESS = "DELETE_BUSINESS_PROCESS";

//QIP
export const STORE_ACCESS_TOKEN = "STORE_ACCESS_TOKEN";

// PerfexD
export const STORE_PERFEXD_UTILITIES = "STORE_PERFEXD_UTILITIES";

// SAP
export const STORE_PRODUCT_LIST = "STORE_PRODUCT_LIST";
export const STORE_SAP_VERSIONS = "STORE_SAP_VERSIONS";
export const STORE_SAP_VERSION_INFO = "STORE_SAP_VERSION_INFO";

// Timeline
export const STORE_HOLIDAYS = "STORE_HOLIDAYS";

// predictions
export const STORE_TESTCASES_PREDICTION = "STORE_TESTCASES_PREDICTION";
export const STORE_DEFECTS_PREDICTION = "STORE_DEFECTS_PREDICTION";

//REM
export const STORE_REM_PICKED_ITEMS = "STORE_REM_PICKED_ITEMS";
